#!/bin/zsh
set -euo pipefail
PROJECT_DIR="${0:A:h:h}"
BUILD_DIR="${WAKEMAC_BUILD_DIR:-/tmp/wakemac-build}"
OUTPUT_DIR="${WAKEMAC_OUTPUT_DIR:-/tmp/wakemac-dist}"
cd "$PROJECT_DIR"
swift build -c release --scratch-path "$BUILD_DIR"
APP="$OUTPUT_DIR/WakeMac.app"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources" "$APP/Contents/Library/LaunchDaemons"
cp "$BUILD_DIR/release/WakeMac" "$APP/Contents/MacOS/WakeMac"
cp "$BUILD_DIR/release/WakeMacPowerHelper" "$APP/Contents/MacOS/WakeMacPowerHelper"
cp "$PROJECT_DIR/Resources/local.orx.WakeMac.PowerHelper.plist" "$APP/Contents/Library/LaunchDaemons/"
cp "$PROJECT_DIR/Info.plist" "$APP/Contents/Info.plist"
cp "$PROJECT_DIR/Assets/AppIcon.icns" "$APP/Contents/Resources/AppIcon.icns"
cp "$PROJECT_DIR/Resources/WakeMac.sdef" "$APP/Contents/Resources/WakeMac.sdef"
codesign --force --options runtime --sign "${WAKEMAC_SIGN_IDENTITY:--}" --identifier local.orx.WakeMac.PowerHelper "$APP/Contents/MacOS/WakeMacPowerHelper"
codesign --force --options runtime --sign "${WAKEMAC_SIGN_IDENTITY:--}" "$APP"
codesign --verify --strict "$APP"
printf '%s\n' "$APP"
